### ISSUE TITLE
Inconsistencies with original Bootstrap 3

### ISSUE THREAD

**Issue by Lomacar** [alademann/bootstrap#2]
Somehow there are a bunch of old 2.x class names in the CSS, like btn-large, instead of btn-lg. And the the glyphicon fonts are like "glyphiconshalflings-regular.eot" when they should be "glyphicons-halflings-regular.eot". Missing a dash.

**Comment by aaronlademann-wf** [comment]
@Lomacar I built current version of this library back when Bootstrap 3 was still in alpha.  They made some pretty sweeping changes as they moved towards RC1 and RC2, and as of right now, I don't have enough time on my hands  to get it all updated. 

In the spirit of open source, however - we obviously accept pull requests if you'd like to contribute.

**Comment by Lomacar** [comment]
OK. Unfortunately I don't know what pull requests are or how to use GitHub, so...

**Comment by alonextou** [comment]
Here you go @Lomacar http://www.codeschool.com/courses/git-real

**Comment by alademann** [comment]
@Lomacar @awc737 I am working to get this project up-to-speed with all the changes that were made leading up to twbs' 3.0.0 release... I've begun work and you can monitor progress on [this branch](https://github.com/alademann/sass-bootstrap/tree/3.0.1_sass-wip)

**Comment by alademann** [comment]
@Lomacar @awc737 repo is now up to date with twbs 3.0.0.  You can install this as a bower package now by running 

``` bash
npm install bower -g

bower install alademann-sass-bootstrap
```

from whatever directory you want to use sass-bootstrap in as a component. 

Checkout README for more information.
