### ISSUE TITLE
Upgrade to 3.1.0?

### ISSUE THREAD

**Issue by hephaestoskin** [alademann/bootstrap#21]
Are there plans to upgrade to Bootstrap 3.1.0?

**Comment by alademann** [comment]
@hephaestoskin no immediate plans - I maintain this repo in my spare time, which has been in rather short supply lately.  We do accept pull requests though :smile:

**Comment by massimopalmieri** [comment]
@hephaestoskin Bootstrap 3.1.0 officially supports SASS

http://blog.getbootstrap.com/2014/01/30/bootstrap-3-1-0-released/

**Comment by hephaestoskin** [comment]
Oh SNAP! Thanks!
