### ISSUE TITLE
Wrong mixing name

### ISSUE THREAD

**Issue by ramono** [alademann/bootstrap#22]
Hi

There's an error in lines 538 and 542 of the _mixins.scss file, where it's including a mixin called "box-shadow", but the actual mixing name in this file was changed to tb_box-shadow in line 132 of the same file. It works because compass has this mixin so is not throwing an error, but I had to remove the inclusion of compass (I don't know why you need compass here at all) and saw the error.

Can I ask, why would you chance mixin names? it is not a 1:1 translation of Bootstrap if it has different names.

**Comment by alademann** [comment]
@ramono - Bootstrap 3.1.0 officially supports SASS... I'd recommend using that if you're needing a 1:1 translation.

http://blog.getbootstrap.com/2014/01/30/bootstrap-3-1-0-released/
