### ISSUE TITLE
Why does this exist?

### ISSUE THREAD

**Issue by nerik** [alademann/bootstrap#25]
Hello,

Correct me if I'm wrong but it looks like the bootstrap team is maintaining a sass version of bootstrap themselves (called 'bootstrap-sass' https://github.com/twbs/bootstrap-sass)

Since this project looks deprecated (no 3.1x), I would like to suggest to close this repository and/or redirect people to the bootstrap-sass repo. There may be many people using a deprecated version of bootstrap (via bower in particular)

Thanks

**Comment by bittner** [comment]
I'd suggest:
1. Fork the repo
2. Change the README
3. Make a pull request

Then everyone will be happy!

**Comment by nerik** [comment]
Yeah sure but that wouldn't fix the main issue which is that :
'bower install sass-bootstrap'
currently installs a deprecated version of bootstrap.

**Comment by alademann** [comment]
I have updated the repo name / readme to indicate that the official repo should be used.  @nerik you should use `bower install bootstrap-sass-official` to install the one maintained by twbs.
