### ISSUE TITLE
What version of twitter bootstrap is used in release 3.0.16?

### ISSUE THREAD

**Issue by pconerly** [alademann/bootstrap#26]
Hi @alademann 

So, there isn't a twitter bootstrap version 3.0.16.  What version of twitter bootstrap does this repo's version `3.0.16` use?  Is it `3.0.0`? `3.0.3` ?

I'm porting off of this library and I'm trying to figure out what version of bootstrap-sass to swap in to replace this.

**Comment by aaronlademann-wf** [comment]
@pconerly `3.0.0` I believe.  However - I would recommend just using the latest `3.x` release from the official [twbs/bootstrap-sass](https://github.com/twbs/bootstrap-sass) (currently `3.3.6`). 

There may be a few minor breaks - but shouldn't be too painful.

The best part is - [Bootstrap `4.0.0` is going to use Sass!](http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/#whats-new) _(they finally came to their senses and stopped using less)_

**Comment by alademann** [comment]
@pconerly `3.0.0` I believe.  However - I would recommend just using the latest `3.x` release from the official [twbs/bootstrap-sass](https://github.com/twbs/bootstrap-sass) repo (currently `3.3.6`). 

There may be a few minor breaks - but shouldn't be too painful.

The best part is - [Bootstrap `4.0.0` is going to use Sass!](http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/#whats-new) _(they finally came to their senses and stopped using less)_
