### ISSUE TITLE
Collapse Animation - On Opening

### ISSUE THREAD

**Issue by Ne-Ne** [alademann/bootstrap#3]
Hey,

As the title states, I have a problem that the animation on opening. It is not the same as on close. Is it possible to use the function to allow to be used for opening animation. Not just the closing?

I want the UI to be the same as content being opened and closed across the site.

Great work on BS3 by the way!

**Comment by alademann** [comment]
Thanks for the bug report. I will address this as part of the [3.0.1](https://github.com/alademann/sass-bootstrap/issues?milestone=1&state=open) release.

**Comment by Ne-Ne** [comment]
Thanks, I can see there is a function that does the animation. However I need a fix?

I have a feeling that max-height may work. What would you recommend?

**Comment by alademann** [comment]
@Ne-Ne - If your HTML markup is compliant with all the requirements shown in twbs' [documentation about the collapse plugin](http://getbootstrap.com/javascript/#collapse), and you don't have any custom CSS affecting the height/max-height/etc... it should just work.

**Comment by Ne-Ne** [comment]
Thanks for replying @alademann . I missed there was a conflict between my JS and the transition.js file.

However I have set the HTML5 Data attr to collapse. However on document load the animation starts (opened -> closed) on every container. I would like the containers to be closed then apply the click toggle to the accordion.

-Neil

**Comment by alademann** [comment]
@Ne-Ne clicking on them doesn't toggle their visibility?

**Comment by Ne-Ne** [comment]
On page load they collapse straight away.

Don't get me wrong the animation (on toggle works fine), but as I have a lot of content within the accordion, as the initial random collapse look obvious.

Using the data attr does this enforce the collapsed element on load or is there a natural delay?

**Comment by alademann** [comment]
The data attribute is hooked into the collapse plugin on domReady I believe - so you would need to hard-code a css class on the containers that are present at time of load that hide that content before the collapse occurs.

**Comment by Ne-Ne** [comment]
That makes sense however I checked the CSS and there is height 0px and overflow hidden (I believe).

Without looking to be a pain in the arse. Would this negate the need for a hardcoded class?

Many thanks

**Comment by alademann** [comment]
Neil,

Please post an example / link to the behavior you're seeing.

**Comment by Ne-Ne** [comment]
I'm working off Mamp Pro, will get a copy on a subdomain in the morning (uk).

Thanks for looking into this.
