### ISSUE TITLE
Missing Mobile Media Queries

### ISSUE THREAD

**Issue by Ne-Ne** [alademann/bootstrap#4]
Hey all,

I noticed that there missing classes or media queries when size hits certain breakpoints for all the spans.

The LESS counter part has all these built in, however I cannot find these in any of the SASS files or documentation?

E.G. - http://getbootstrap.com/css/#grid

Am I being a muppet here?

**Comment by alademann** [comment]
@Ne-Ne - as I mentioned in the previous issue.... I built this port when Bootstrap 3.0 was still in beta.  They added a TON of stuff during the RC process - and I have not updated my port completely. 

Its a work in progress... but I have not yet started mapping the changes from their LESS files into my SCSS files.

**Comment by Ne-Ne** [comment]
Ah that explains the lack of documentation on the Grid layout, this should really be explained in the modular section of the documentation site, especially on parts which you feel need more work / new additions to negate any of these doubles issue threads.

I can't imagine how tedious the process of responding to multiple, solved issues..

I really need these features. If you need a beta tester I will happy do it. With reference to multiple browsers and SCSS code. I may be fairly new to Git but comfortable with SCSS & OOCSS. At present do you have a public timeline on this project (gantt chart / online app) or is it adhoc?

Many thanks.

**Comment by alademann** [comment]
@Ne-Ne this repo has milestones - and currently the milestone i'm targeting for getting up-to-date with bootstrap's final 3.0.0 RC is [here](https://github.com/alademann/sass-bootstrap/issues/milestones)

I have finished getting the docs up-to-date - just in the process of converting the .less syntax to .scss (which is not turnkey)

**Comment by alademann** [comment]
To reiterate @Ne-Ne - if you are familiar with SCSS, we do accept pull requests.

**Comment by Ne-Ne** [comment]
I can understand, I will look into github features more so.

If I can help you out I will.

Thanks for the update!

**Comment by shariffrb** [comment]
I have just converted all of the less to scss.  I had been facing this issue in the following

@mixin input-size($input-height, $padding-vertical, $padding-horizontal, $font-size, $line-height, $border-radius, $css-class) {
  height: $input-height;
  padding: $padding-vertical $padding-horizontal;
  font-size: $font-size;
  line-height: $line-height;
  border-radius: $border-radius;

  select#{$css-class} {
    height: $input-height;
    line-height: $input-height;
  }

  textarea#{$css-class} {
    height: auto;
  }
}

the error was $css-class and its a missing arugment.

for time being I have just removed the $css-class variable and also #{$css-class} from select and textarea, to start compiling css.

**Comment by alademann** [comment]
@shariffrb the reason the css-class parameter was present was because twbs' less mixin used the following pattern to add the classname they wanted to elements... 

``` less
@mixin input-size(...) {
    input&,
    select& {
        ...
    }
}
```

The problem is that with sass - the `&` operator cannot be placed on an element like that.  Therefore, in the sass version - we need each instance of `@include input-size` to pass a css class parameter so we can do this: 

``` scss
@mixin input-size(...) {
    input#{$css-class},
    select#{$css-class} {
        ...
    }
}
```

Are you working off of the [3.0.1_sass-wip](https://github.com/alademann/sass-bootstrap/tree/3.0.1_sass-wip) branch? If not, please do - that is where the PR you're working on should go.

**Comment by alademann** [comment]
There is another mixin (can't remember off the top of my head) in twbs' mixins file that uses this same `element&` pattern that we'll have to adjust to use via parameterizing the css class.  I think it may be something with table cells or something.

**Comment by alademann** [comment]
@Ne-Ne the repo is now up to date with twbs 3.0.0.  You can install this as a bower package now by running 

``` bash
npm install bower -g

bower install alademann-sass-bootstrap
```

from whatever directory you want to use sass-bootstrap in as a component. 

Checkout README for more information.

You can also update your fork if thats how you're doing it.
