### ISSUE TITLE
gem

### ISSUE THREAD

**Issue by spenoir** [alademann/bootstrap#5]
Do you have a gem install?

**Comment by alademann** [comment]
@spenoir - there is no Gem install for this repo.  As part of the [3.0.1 release](https://github.com/alademann/sass-bootstrap/issues/milestones), there will be a Bower install, though.

**Comment by alademann** [comment]
@spenoir the 3.0.1 release is out... You can install this as a bower package now by running 

``` bash
npm install bower -g

bower install alademann-sass-bootstrap
```

from whatever directory you want to use sass-bootstrap in as a component. 

Checkout README for more information.
