### ISSUE TITLE
Feature Request: prefix to bootstrap classes

### ISSUE THREAD

**Issue by d6u** [alademann/bootstrap#9]
Do you have support to add prefix to bootstrap classes?

Thank you

**Comment by alademann** [comment]
Not sure I'm following - what do you mean by bootstrap classes?  Can you give me an example of what you're wanting to do?

**Comment by d6u** [comment]
@alademann sorry for the confusion. What I mean is:

For `.form-control` class, could I make it become `.my-own-namespace-form-control` when I compile SCSS file into CSS file.

Thank you.

**Comment by aaronlademann-wf** [comment]
Ahh... I see - no, that is not currently something that I am willing to undertake... I'm confused as to why you would need the classes to be customized... If you'd like to take a crack at it and submit a PR - be my guest.

**Comment by d6u** [comment]
@aaronlademann-wf thank you for your response
